// Curated concept chunks used to ground each generated question (simple RAG:
// one chunk is retrieved per request and passed to the model as context).
module.exports = [
  // --- Data structures & algorithms ---
  { id: "ds-1", category: "Data Structures", topic: "Hash Tables", content: "A hash table maps keys to values using a hash function to compute an index into an array of buckets. Average-case lookup, insert, and delete are O(1), but collisions (two keys hashing to the same bucket) can degrade this to O(n) in the worst case. Collision resolution strategies include chaining (linked lists per bucket) and open addressing (probing for the next free slot)." },
  { id: "ds-2", category: "Data Structures", topic: "Binary Search Trees", content: "A binary search tree keeps every left subtree less than its node and every right subtree greater, giving O(log n) search, insert, and delete when balanced. An unbalanced tree (e.g. built from sorted input) degrades to a linked list with O(n) operations, which is why self-balancing variants like AVL or red-black trees exist." },
  { id: "ds-3", category: "Algorithms", topic: "Big-O Complexity", content: "Big-O notation describes how an algorithm's runtime or memory use grows as input size increases, focusing on the dominant term and ignoring constants. O(1) is constant, O(log n) grows slowly (e.g. binary search), O(n) is linear, O(n log n) is typical of good sorting algorithms, and O(n^2) or worse indicates nested iteration over the input." },
  { id: "ds-4", category: "Algorithms", topic: "Dynamic Programming", content: "Dynamic programming solves problems by breaking them into overlapping subproblems and storing (memoizing) their results to avoid recomputation. It applies when a problem has optimal substructure (an optimal solution can be built from optimal solutions to subproblems) and overlapping subproblems, as in Fibonacci, knapsack, or edit distance." },
  { id: "ds-5", category: "Algorithms", topic: "Graph Traversal", content: "Breadth-first search (BFS) explores a graph level by level using a queue and finds the shortest path in an unweighted graph. Depth-first search (DFS) explores as far as possible along each branch using a stack (or recursion) before backtracking, and is well suited to cycle detection and topological sorting." },
  { id: "ds-6", category: "Algorithms", topic: "Sorting Algorithms", content: "Comparison sorts like merge sort and quicksort run in O(n log n) average time; merge sort is stable and guarantees O(n log n) worst case at the cost of O(n) extra space, while quicksort is typically faster in practice but degrades to O(n^2) on adversarial pivots. Counting sort and radix sort can beat O(n log n) but only work for restricted input types like small-range integers." },

  // --- System design ---
  { id: "sd-1", category: "System Design", topic: "Load Balancing", content: "A load balancer distributes incoming requests across multiple backend servers to improve availability and throughput. Common strategies include round robin, least connections, and consistent hashing (which minimizes redistribution when servers are added or removed, important for caching layers)." },
  { id: "sd-2", category: "System Design", topic: "Caching Strategies", content: "Caching stores frequently accessed data closer to the consumer to reduce latency and backend load. Cache-aside (lazy loading) fetches from the source on a miss and populates the cache, write-through writes to cache and source simultaneously, and write-back writes to cache first and flushes to source later, trading durability for write speed." },
  { id: "sd-3", category: "System Design", topic: "CAP Theorem", content: "The CAP theorem states that a distributed system can only guarantee two of three properties during a network partition: consistency (every read gets the latest write), availability (every request gets a response), and partition tolerance (the system keeps working despite dropped or delayed messages). Since partitions are unavoidable at scale, real systems choose between CP (favoring consistency) and AP (favoring availability)." },
  { id: "sd-4", category: "System Design", topic: "Message Queues", content: "A message queue decouples producers from consumers by buffering messages between them, allowing services to scale independently and absorb traffic spikes. Queues can offer at-least-once delivery (messages may be processed more than once, requiring idempotent consumers) or exactly-once semantics, which is harder to guarantee and usually more expensive." },
  { id: "sd-5", category: "System Design", topic: "Database Sharding", content: "Sharding splits a large dataset across multiple database instances, each holding a subset of the rows, to scale writes and storage beyond a single machine. A shard key determines how data is distributed; a poorly chosen key can create hot shards that receive disproportionate traffic, undermining the benefit of sharding." },
  { id: "sd-6", category: "System Design", topic: "Rate Limiting", content: "Rate limiting caps how many requests a client can make in a given window to protect a service from overload or abuse. The token bucket algorithm allows bursts up to a bucket capacity while refilling tokens at a steady rate, while the sliding window log or counter approach tracks requests within a rolling time window for smoother enforcement." },

  // --- Databases ---
  { id: "db-1", category: "Databases", topic: "ACID Transactions", content: "ACID describes guarantees a database transaction provides: atomicity (all operations succeed or none do), consistency (the database moves between valid states), isolation (concurrent transactions don't interfere, enforced via isolation levels like read committed or serializable), and durability (committed data survives crashes)." },
  { id: "db-2", category: "Databases", topic: "Database Indexing", content: "An index is a separate data structure, typically a B-tree, that lets the database find rows matching a query without scanning the whole table. Indexes speed up reads but slow down writes (since the index must be updated too) and consume extra storage, so they are usually added on columns used frequently in WHERE clauses or joins." },
  { id: "db-3", category: "Databases", topic: "Normalization", content: "Database normalization organizes relational tables to reduce data redundancy and avoid update anomalies, typically by progressing through normal forms (1NF removes repeating groups, 2NF removes partial dependencies, 3NF removes transitive dependencies). Denormalization intentionally reintroduces redundancy to optimize read performance at the cost of update complexity." },
  { id: "db-4", category: "Databases", topic: "SQL vs NoSQL", content: "Relational (SQL) databases enforce a fixed schema and strong consistency, and excel at complex joins and transactions. NoSQL databases (document, key-value, column-family, graph) relax schema constraints and often trade strict consistency for horizontal scalability and flexible data models, fitting workloads with high write volume or evolving schemas." },

  // --- OOP & design patterns ---
  { id: "oop-1", category: "OOP", topic: "SOLID Principles", content: "SOLID is a set of five object-oriented design principles: Single responsibility (a class should have one reason to change), Open/closed (open for extension, closed for modification), Liskov substitution (subtypes must be usable wherever their base type is expected), Interface segregation (prefer many specific interfaces over one general one), and Dependency inversion (depend on abstractions, not concrete implementations)." },
  { id: "oop-2", category: "Design Patterns", topic: "Singleton Pattern", content: "The singleton pattern restricts a class to a single instance and provides a global access point to it, often used for shared resources like configuration or connection pools. It is frequently criticized for introducing hidden global state and making unit testing harder, since it's difficult to substitute a mock instance." },
  { id: "oop-3", category: "Design Patterns", topic: "Observer Pattern", content: "The observer pattern defines a one-to-many dependency where a subject notifies a list of registered observers automatically when its state changes, without the subject needing to know their concrete types. It underlies event systems, pub/sub messaging, and reactive UI frameworks." },
  { id: "oop-4", category: "OOP", topic: "Composition vs Inheritance", content: "Inheritance creates an 'is-a' relationship where a subclass reuses and extends a parent class's behavior, but can lead to fragile hierarchies as depth increases. Composition creates a 'has-a' relationship by building objects out of other objects' behavior, favored by the principle 'favor composition over inheritance' because it keeps components independently testable and swappable." },

  // --- Concurrency & networking ---
  { id: "cc-1", category: "Concurrency", topic: "Race Conditions", content: "A race condition occurs when multiple threads or processes access shared state concurrently and the outcome depends on the unpredictable timing of their execution. It is typically prevented with synchronization primitives like locks, mutexes, or atomic operations, though excessive locking can introduce deadlocks or reduce throughput." },
  { id: "cc-2", category: "Concurrency", topic: "Deadlocks", content: "A deadlock happens when two or more threads each hold a resource the other needs and neither can proceed, permanently blocking. The four necessary conditions (mutual exclusion, hold and wait, no preemption, circular wait) are the basis for deadlock prevention strategies, such as always acquiring locks in a fixed global order." },
  { id: "net-1", category: "Networking", topic: "TCP vs UDP", content: "TCP is connection-oriented and guarantees ordered, reliable delivery through acknowledgments and retransmission, making it suitable for web traffic and file transfer but adding latency overhead. UDP is connectionless with no delivery guarantees, offering lower latency and less overhead, which suits real-time applications like video calls or gaming where occasional packet loss is tolerable." },

  // --- Testing & practices ---
  { id: "test-1", category: "Testing", topic: "Unit vs Integration Testing", content: "Unit tests verify a single function or class in isolation, typically using mocks or stubs for dependencies, and run fast enough to execute on every code change. Integration tests verify that multiple components work together correctly (e.g. a service talking to a real database), catching interface mismatches that unit tests, with their mocked dependencies, cannot." },
  { id: "test-2", category: "Software Practices", topic: "CI/CD", content: "Continuous integration automatically builds and tests code on every commit to catch integration problems early, while continuous delivery/deployment automates releasing that code to staging or production once it passes those checks. Together they reduce the risk and manual effort of shipping software by replacing large, infrequent releases with small, frequently verified ones." },

  // --- ML fundamentals ---
  { id: "ml-1", category: "ML Fundamentals", topic: "Overfitting vs Underfitting", content: "Overfitting occurs when a model learns noise and specific patterns in the training data that don't generalize, showing low training error but high validation error. Underfitting occurs when a model is too simple to capture the underlying pattern, showing high error on both training and validation data. Regularization, more data, or simpler models address overfitting; more capacity or features address underfitting." },
  { id: "ml-2", category: "ML Fundamentals", topic: "Bias-Variance Tradeoff", content: "Bias is error from overly simplistic assumptions in a model (underfitting), while variance is error from sensitivity to small fluctuations in the training set (overfitting). Total expected error decomposes into bias squared, variance, and irreducible noise, so reducing one often increases the other, which is why model complexity must be tuned rather than maximized." },
  { id: "ml-3", category: "ML Fundamentals", topic: "Regularization (L1/L2)", content: "Regularization adds a penalty term to the loss function to discourage overly complex models and reduce overfitting. L1 (Lasso) penalizes the sum of absolute weight values and tends to push some weights exactly to zero, performing implicit feature selection. L2 (Ridge) penalizes the sum of squared weights, shrinking them smoothly toward zero without eliminating them entirely." },
  { id: "ml-4", category: "ML Fundamentals", topic: "Cross-Validation", content: "K-fold cross-validation splits the training data into k subsets, trains on k-1 of them and validates on the remaining one, repeating k times so every subset is used for validation once. Averaging the resulting scores gives a more reliable estimate of a model's generalization performance than a single train/validation split, at the cost of k times the training compute." },
  { id: "ml-5", category: "Model Evaluation", topic: "Precision vs Recall", content: "Precision is the fraction of predicted positives that are actually positive (TP / (TP + FP)), while recall is the fraction of actual positives the model correctly identifies (TP / (TP + FN)). There is usually a tradeoff between them controlled by the classification threshold; the F1 score, their harmonic mean, balances both when neither alone is a sufficient metric." },
  { id: "ml-6", category: "Model Evaluation", topic: "Confusion Matrix", content: "A confusion matrix tabulates a classifier's predictions against actual labels, breaking them into true positives, true negatives, false positives, and false negatives. It is the basis for deriving accuracy, precision, recall, and specificity, and is especially useful for spotting class imbalance problems that accuracy alone would hide." },
  { id: "ml-7", category: "Optimization", topic: "Gradient Descent", content: "Gradient descent iteratively updates model parameters in the direction that most reduces the loss function, scaled by a learning rate. Too high a learning rate can overshoot minima and diverge; too low makes convergence slow. Variants like mini-batch and stochastic gradient descent trade off gradient accuracy against computation per update, and momentum-based optimizers like Adam adapt the effective learning rate per parameter." },
  { id: "ml-8", category: "Optimization", topic: "Learning Rate Scheduling", content: "A learning rate schedule adjusts the learning rate during training, commonly starting higher for fast initial progress and decaying it (step decay, cosine annealing, or warm-up followed by decay) as training progresses to allow finer convergence near a minimum. Poor scheduling can cause a model to plateau early or oscillate without converging." },

  // --- Neural networks & deep learning ---
  { id: "nn-1", category: "Neural Networks", topic: "Backpropagation", content: "Backpropagation computes the gradient of the loss with respect to every weight in a neural network by applying the chain rule backward from the output layer to the input layer, reusing intermediate results for efficiency. This gradient is then used by an optimizer like gradient descent to update the weights." },
  { id: "nn-2", category: "Neural Networks", topic: "Activation Functions", content: "Activation functions introduce non-linearity so a neural network can model complex relationships rather than collapsing into a single linear transformation. ReLU (max(0, x)) is cheap to compute and avoids vanishing gradients for positive inputs but can 'die' for negative inputs; sigmoid and tanh saturate at extremes, causing vanishing gradients in deep networks." },
  { id: "nn-3", category: "Neural Networks", topic: "Vanishing/Exploding Gradients", content: "In deep networks, gradients can shrink toward zero (vanishing) or grow uncontrollably (exploding) as they're propagated backward through many layers, especially with saturating activations or poorly scaled weights. Techniques like careful weight initialization, batch normalization, residual connections, and gradient clipping mitigate these issues." },
  { id: "nn-4", category: "Deep Learning", topic: "Convolutional Neural Networks", content: "CNNs use learnable filters that slide across an input (typically an image) to detect local patterns like edges or textures, with parameter sharing across spatial positions making them far more efficient than fully connected layers for grid-like data. Pooling layers then downsample feature maps to reduce dimensionality and add translation invariance." },
  { id: "nn-5", category: "Deep Learning", topic: "Transformer Attention", content: "Self-attention lets a model weigh the relevance of every other token in a sequence when encoding a given token, computed via query, key, and value projections, rather than processing tokens strictly in order as RNNs do. This parallelizability and ability to capture long-range dependencies is why transformers replaced recurrent architectures in most modern NLP and increasingly vision tasks." },
  { id: "nn-6", category: "Deep Learning", topic: "Dropout", content: "Dropout randomly zeroes a fraction of neuron activations during each training step, forcing the network to not rely too heavily on any single neuron and reducing co-adaptation between them. This acts as a regularizer that reduces overfitting; dropout is disabled at inference time, with activations typically rescaled to account for its absence." },

  // --- MLOps & applied ML ---
  { id: "mlops-1", category: "MLOps", topic: "Train/Validation/Test Split", content: "The training set is used to fit model parameters, the validation set is used to tune hyperparameters and make model-selection decisions without touching the test set, and the test set gives a final, unbiased estimate of generalization performance, evaluated only once model development is finished." },
  { id: "mlops-2", category: "MLOps", topic: "Data Leakage", content: "Data leakage occurs when information that would not be available at prediction time (such as future data, or features derived using the target) leaks into training, causing inflated validation performance that fails to hold in production. Common sources include preprocessing (e.g. scaling) fit on the full dataset before splitting, or duplicate records spanning train and test sets." },
  { id: "mlops-3", category: "MLOps", topic: "Model Drift", content: "Model drift is the degradation of a deployed model's performance over time as the statistical properties of incoming data diverge from the training distribution (data drift) or the relationship between features and target changes (concept drift). Monitoring input distributions and prediction quality in production, with scheduled retraining, is the standard mitigation." },
  { id: "mlops-4", category: "Applied ML", topic: "Feature Engineering", content: "Feature engineering transforms raw data into representations that make patterns easier for a model to learn, such as encoding categorical variables, scaling numeric features, or creating interaction terms. Well-chosen features often improve performance more than switching model architectures, especially for classical ML models that don't learn representations automatically the way deep networks do." },
];
